# Generated by Django 5.2.12 on 2026-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_api_use",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest API token usage date"
            ),
        ),
    ]
