# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

# Opt out of pull request validation
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
  # Azure DevOps repository
  - repository: tiedonohjaus-pipelines
    type: git
    # Azure DevOps project/repository
    name: tiedonohjaus/tiedonohjaus-pipelines

extends:
  template: azure-pipelines-tiedonohjaus-api-dev.yml@tiedonohjaus-pipelines
