services:
  postgres:
    image: postgres:14.7
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: helerm
    ports:
      - '5432:5432'
    volumes:
      - helerm_postgres-data-volume:/var/lib/postgresql/data
    container_name: helerm_postgres

  elasticsearch:
    build:
      context: .
      dockerfile: .docker/elasticsearch/Dockerfile
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.watermark.low=97%
      - cluster.routing.allocation.disk.watermark.high=98%
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Djava.security.policy=file:/usr/share/elasticsearch/plugins/elasticsearch-analysis-voikko/plugin-security.policy"
    container_name: helerm_elasticsearch

  django:
    build:
      context: .
      dockerfile: .docker/django/Dockerfile
    environment:
      ELASTICSEARCH_HOST: helerm_elasticsearch
    env_file:
      - .docker/django/.env
    volumes:
      - .:/app
    ports:
      - '8080:8000'
    depends_on:
      - postgres
    container_name: helerm

volumes:
  helerm_postgres-data-volume:
