FROM elasticsearch:8.11.1

RUN bin/elasticsearch-plugin install https://github.com/EvidentSolutions/elasticsearch-analysis-raudikko/releases/download/v0.1.2/elasticsearch-analysis-raudikko-0.1.2-es8.11.1.zip
