# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'actions',
                'verbose_name': 'action',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('function_id', models.CharField(max_length=16, verbose_name='function ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metarecord.Function', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'functions',
                'verbose_name': 'function',
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personaldata_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personaldata_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'personal data',
                'verbose_name': 'personal data',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phase_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='metarecord.Function', verbose_name='function')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phase_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('personal_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='metarecord.PersonalData', verbose_name='personal data')),
            ],
            options={
                'verbose_name_plural': 'phases',
                'verbose_name': 'phase',
            },
        ),
        migrations.CreateModel(
            name='ProtectionClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protectionclass_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protectionclass_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'protection classes',
                'verbose_name': 'protection class',
            },
        ),
        migrations.CreateModel(
            name='PublicityClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicityclass_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicityclass_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'publicity classes',
                'verbose_name': 'publicity class',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('type', models.CharField(max_length=64, verbose_name='type')),
                ('type_specifier', models.CharField(blank=True, max_length=256, verbose_name='type specifier')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metarecord.Action', verbose_name='action')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('personal_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metarecord.PersonalData', verbose_name='personal data')),
                ('protection_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metarecord.ProtectionClass', verbose_name='protection class')),
                ('publicity_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metarecord.PublicityClass', verbose_name='publicity class')),
            ],
            options={
                'verbose_name_plural': 'records',
                'verbose_name': 'record',
            },
        ),
        migrations.CreateModel(
            name='RetentionPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('value', models.IntegerField(verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retentionperiod_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retentionperiod_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'retention periods',
                'verbose_name': 'retention period',
            },
        ),
        migrations.CreateModel(
            name='RetentionReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retentionreason_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retentionreason_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'retention reasons',
                'verbose_name': 'retention reason',
            },
        ),
        migrations.CreateModel(
            name='SecurityPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('value', models.IntegerField(verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='securityperiod_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='securityperiod_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'security periods',
                'verbose_name': 'security period',
            },
        ),
        migrations.CreateModel(
            name='SecurityReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='securityreason_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='securityreason_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'security reasons',
                'verbose_name': 'security reasons',
            },
        ),
        migrations.CreateModel(
            name='SocialSecurityNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialsecuritynumber_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialsecuritynumber_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'social security numbers',
                'verbose_name': 'social security number',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='retention_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metarecord.RetentionPeriod', verbose_name='retention period'),
        ),
        migrations.AddField(
            model_name='record',
            name='retention_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metarecord.RetentionReason', verbose_name='retention reason'),
        ),
        migrations.AddField(
            model_name='record',
            name='security_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metarecord.SecurityPeriod', verbose_name='security period'),
        ),
        migrations.AddField(
            model_name='record',
            name='security_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metarecord.SecurityReason', verbose_name='security reason'),
        ),
        migrations.AddField(
            model_name='record',
            name='social_security_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metarecord.SocialSecurityNumber', verbose_name='social security number'),
        ),
        migrations.AddField(
            model_name='phase',
            name='protection_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='metarecord.ProtectionClass', verbose_name='protection class'),
        ),
        migrations.AddField(
            model_name='phase',
            name='publicity_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='metarecord.PublicityClass', verbose_name='publicity class'),
        ),
        migrations.AddField(
            model_name='phase',
            name='retention_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='metarecord.RetentionPeriod', verbose_name='retention period'),
        ),
        migrations.AddField(
            model_name='phase',
            name='retention_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='metarecord.RetentionReason', verbose_name='retention reason'),
        ),
        migrations.AddField(
            model_name='phase',
            name='security_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='metarecord.SecurityPeriod', verbose_name='security period'),
        ),
        migrations.AddField(
            model_name='phase',
            name='security_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='metarecord.SecurityReason', verbose_name='security reason'),
        ),
        migrations.AddField(
            model_name='phase',
            name='social_security_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='metarecord.SocialSecurityNumber', verbose_name='social security number'),
        ),
        migrations.AddField(
            model_name='function',
            name='personal_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='metarecord.PersonalData', verbose_name='personal data'),
        ),
        migrations.AddField(
            model_name='function',
            name='protection_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='metarecord.ProtectionClass', verbose_name='protection class'),
        ),
        migrations.AddField(
            model_name='function',
            name='publicity_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='metarecord.PublicityClass', verbose_name='publicity class'),
        ),
        migrations.AddField(
            model_name='function',
            name='retention_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='metarecord.RetentionPeriod', verbose_name='retention period'),
        ),
        migrations.AddField(
            model_name='function',
            name='retention_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='metarecord.RetentionReason', verbose_name='retention reason'),
        ),
        migrations.AddField(
            model_name='function',
            name='security_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='metarecord.SecurityPeriod', verbose_name='security period'),
        ),
        migrations.AddField(
            model_name='function',
            name='security_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='metarecord.SecurityReason', verbose_name='security reason'),
        ),
        migrations.AddField(
            model_name='function',
            name='social_security_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='metarecord.SocialSecurityNumber', verbose_name='social security number'),
        ),
        migrations.AddField(
            model_name='action',
            name='personal_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='metarecord.PersonalData', verbose_name='personal data'),
        ),
        migrations.AddField(
            model_name='action',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='metarecord.Phase', verbose_name='phase'),
        ),
        migrations.AddField(
            model_name='action',
            name='protection_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='metarecord.ProtectionClass', verbose_name='protection class'),
        ),
        migrations.AddField(
            model_name='action',
            name='publicity_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='metarecord.PublicityClass', verbose_name='publicity class'),
        ),
        migrations.AddField(
            model_name='action',
            name='retention_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='metarecord.RetentionPeriod', verbose_name='retention period'),
        ),
        migrations.AddField(
            model_name='action',
            name='retention_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='metarecord.RetentionReason', verbose_name='retention reason'),
        ),
        migrations.AddField(
            model_name='action',
            name='security_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='metarecord.SecurityPeriod', verbose_name='security period'),
        ),
        migrations.AddField(
            model_name='action',
            name='security_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='metarecord.SecurityReason', verbose_name='security reason'),
        ),
        migrations.AddField(
            model_name='action',
            name='social_security_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='metarecord.SocialSecurityNumber', verbose_name='social security number'),
        ),
    ]
