# Generated by Django 3.1.5 on 2021-02-15 09:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("metarecord", "0001_squashed_0048"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeValidationRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time of creation"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="time of modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("validation_json", models.JSONField()),
                (
                    "content_type",
                    models.OneToOneField(
                        help_text="Relation to the chosen type: Action (Toimenpide) / Function (Käsittelyprosessi) / Phase (Käsittelyvaihe) / Record (Asiakirja). Relation to 'Attribute validation rule' is applied for each of the types.",
                        limit_choices_to=models.Q(
                            ("model", "action"),
                            ("model", "function"),
                            ("model", "phase"),
                            ("model", "record"),
                            ("model", "attributevalidationrule"),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "attribute validation rule",
                "verbose_name_plural": "attribute validation rules",
                "ordering": ("content_type",),
            },
        ),
    ]
