# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metarecord", "0003_auto_20160417_1157"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInformation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of modification",
                    ),
                ),
                ("value", models.CharField(max_length=256, verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additionalinformation_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additionalinformation_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "additional information",
                "verbose_name_plural": "additional information",
            },
        ),
        migrations.CreateModel(
            name="InformationSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of modification",
                    ),
                ),
                ("value", models.CharField(max_length=256, verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informationsystem_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informationsystem_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "information system",
                "verbose_name_plural": "information systems",
            },
        ),
        migrations.CreateModel(
            name="PaperRecordArchiveRetentionPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of modification",
                    ),
                ),
                ("value", models.CharField(max_length=256, verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordarchiveretentionperiod_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordarchiveretentionperiod_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper record archive retention period",
                "verbose_name_plural": "paper record archive retention periods",
            },
        ),
        migrations.CreateModel(
            name="PaperRecordRetentionLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of modification",
                    ),
                ),
                ("value", models.CharField(max_length=256, verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordretentionlocation_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordretentionlocation_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper record retention location",
                "verbose_name_plural": "paper record retention locations",
            },
        ),
        migrations.CreateModel(
            name="PaperRecordRetentionOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of modification",
                    ),
                ),
                ("value", models.CharField(max_length=256, verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordretentionorder_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordretentionorder_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper record retention order",
                "verbose_name_plural": "paper record retention orders",
            },
        ),
        migrations.CreateModel(
            name="PaperRecordRetentionResponsiblePerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of modification",
                    ),
                ),
                ("value", models.CharField(max_length=256, verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordretentionresponsibleperson_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordretentionresponsibleperson_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper record retention responsible person",
                "verbose_name_plural": "paper record retention responsible persons",
            },
        ),
        migrations.CreateModel(
            name="PaperRecordWorkplaceRetentionPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of modification",
                    ),
                ),
                ("value", models.CharField(max_length=256, verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordworkplaceretentionperiod_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paperrecordworkplaceretentionperiod_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper record workplace retention period",
                "verbose_name_plural": "paper record workplace retention periods",
            },
        ),
        migrations.CreateModel(
            name="RetentionCalculationBasis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of modification",
                    ),
                ),
                ("value", models.CharField(max_length=256, verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retentioncalculationbasis_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retentioncalculationbasis_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "retention calculation basis",
                "verbose_name_plural": "retention calculation bases",
            },
        ),
        migrations.CreateModel(
            name="SecurityPeriodCalculationBasis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of modification",
                    ),
                ),
                ("value", models.CharField(max_length=256, verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="securityperiodcalculationbasis_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="securityperiodcalculationbasis_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "security period calculation basis",
                "verbose_name_plural": "security period calculation bases",
            },
        ),
        migrations.AddField(
            model_name="action",
            name="additional_information",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="metarecord.AdditionalInformation",
                verbose_name="additional information",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="information_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="metarecord.InformationSystem",
                verbose_name="information system",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="retention_calculation_basis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="metarecord.RetentionCalculationBasis",
                verbose_name="retention calculation basis",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="security_period_calculation_basis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="metarecord.SecurityPeriodCalculationBasis",
                verbose_name="security period calculation basis",
            ),
        ),
        migrations.AddField(
            model_name="function",
            name="additional_information",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functions",
                to="metarecord.AdditionalInformation",
                verbose_name="additional information",
            ),
        ),
        migrations.AddField(
            model_name="function",
            name="information_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functions",
                to="metarecord.InformationSystem",
                verbose_name="information system",
            ),
        ),
        migrations.AddField(
            model_name="function",
            name="retention_calculation_basis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functions",
                to="metarecord.RetentionCalculationBasis",
                verbose_name="retention calculation basis",
            ),
        ),
        migrations.AddField(
            model_name="function",
            name="security_period_calculation_basis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functions",
                to="metarecord.SecurityPeriodCalculationBasis",
                verbose_name="security period calculation basis",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="additional_information",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="metarecord.AdditionalInformation",
                verbose_name="additional information",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="information_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="metarecord.InformationSystem",
                verbose_name="information system",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="retention_calculation_basis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="metarecord.RetentionCalculationBasis",
                verbose_name="retention calculation basis",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="security_period_calculation_basis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="metarecord.SecurityPeriodCalculationBasis",
                verbose_name="security period calculation basis",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="additional_information",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="metarecord.AdditionalInformation",
                verbose_name="additional information",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="information_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="metarecord.InformationSystem",
                verbose_name="information system",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="paper_record_archive_retention_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="metarecord.PaperRecordArchiveRetentionPeriod",
                verbose_name="paper record archive retention period",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="paper_record_retention_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="metarecord.PaperRecordRetentionLocation",
                verbose_name="paper record retention location",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="paper_record_retention_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="metarecord.PaperRecordRetentionOrder",
                verbose_name="paper record retention order",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="paper_record_retention_responsible_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="metarecord.PaperRecordRetentionResponsiblePerson",
                verbose_name="paper record retention location",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="paper_record_workplace_retention_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="metarecord.PaperRecordWorkplaceRetentionPeriod",
                verbose_name="paper record workplace retention period",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="retention_calculation_basis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="metarecord.RetentionCalculationBasis",
                verbose_name="retention calculation basis",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="security_period_calculation_basis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="metarecord.SecurityPeriodCalculationBasis",
                verbose_name="security period calculation basis",
            ),
        ),
    ]
