# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metarecord", "0006_new_data_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="is_free_text",
            field=models.BooleanField(default=False, verbose_name="is free text"),
        ),
    ]
