# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metarecord', '0016_add_attribute_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='type',
        ),
        migrations.DeleteModel(
            name='RecordType',
        ),

    ]
