# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-15 18:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metarecord', '0025_add_attribute_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='function',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='record',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, verbose_name='attributes'),
        ),
    ]
