# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("metarecord", "0027_add_classification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="function",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="function",
            name="function_id",
        ),
        migrations.AlterField(
            model_name="function",
            name="name",
            field=models.CharField(verbose_name="name", max_length=256, blank=True),
        ),
        migrations.AlterField(
            model_name="classification",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="metarecord.Classification",
                verbose_name="parent",
            ),
        ),
    ]
