# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metarecord', '0029_add_db_index_for_uuids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'permissions': (('can_edit', 'Can edit'), ('can_review', 'Can review'), ('can_approve', 'Can approve'), ('can_view_modified_by', 'Can view modified by')), 'verbose_name': 'function', 'verbose_name_plural': 'functions'},
        ),
    ]
