# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("metarecord", "0033_change_attributes_fields_to_jsonb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="function",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functions",
                to="metarecord.Classification",
                verbose_name="classification",
            ),
        ),
    ]
