# Generated by Django 2.0.1 on 2018-04-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metarecord', '0037_update_function_modified_by_to_latest_metadata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
    ]
