# Generated by Django 2.2 on 2019-05-06 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metarecord', '0041_excessmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkupdate',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulkupdate_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
    ]
