# Generated by Django 2.2.5 on 2019-12-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metarecord", "0042_bulkupdate_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="help_text",
            field=models.TextField(blank=True, verbose_name="help text"),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="name",
            field=models.CharField(blank=True, max_length=256, verbose_name="name"),
        ),
    ]
