# Generated by Django 2.2.12 on 2020-04-30 08:11

from django.db import migrations
from django.db.models import OuterRef, Subquery, Value as V
from django.db.models.functions import Coalesce, Concat, Trim


def populate_user_name_field(apps, field_name, model_class):
    """
    Populate related user's full name to equivalent char field prefixed with
    single underscore. The char field is expected to be in the same table as
    the foreign key.
    """
    User = apps.get_model("users", "User")
    char_field_name = "_%s" % field_name

    full_name = (
        User.objects.filter(pk=OuterRef(field_name))
        .annotate(full_name=Trim(Concat("first_name", V(" "), "last_name")))
        .values_list("full_name")[:1]
    )

    model_class.objects.exclude(**{field_name: None}).update(
        **{char_field_name: Subquery(full_name)}
    )


def populate_function_user_name_fields(apps, schema_editor):
    Function = apps.get_model("metarecord", "Function")
    populate_user_name_field(apps, "created_by", Function)
    populate_user_name_field(apps, "modified_by", Function)


def populate_phase_user_name_fields(apps, schema_editor):
    Phase = apps.get_model("metarecord", "Phase")
    populate_user_name_field(apps, "created_by", Phase)
    populate_user_name_field(apps, "modified_by", Phase)


def populate_action_user_name_fields(apps, schema_editor):
    Action = apps.get_model("metarecord", "Action")
    populate_user_name_field(apps, "created_by", Action)
    populate_user_name_field(apps, "modified_by", Action)


def populate_record_user_name_fields(apps, schema_editor):
    Record = apps.get_model("metarecord", "Record")
    populate_user_name_field(apps, "created_by", Record)
    populate_user_name_field(apps, "modified_by", Record)


def populate_bulk_update_user_name_fields(apps, schema_editor):
    BulkUpdate = apps.get_model("metarecord", "BulkUpdate")
    populate_user_name_field(apps, "approved_by", BulkUpdate)
    populate_user_name_field(apps, "created_by", BulkUpdate)
    populate_user_name_field(apps, "modified_by", BulkUpdate)


def populate_metadata_version_user_name_fields(apps, schema_editor):
    MetadataVersion = apps.get_model("metarecord", "MetadataVersion")
    populate_user_name_field(apps, "modified_by", MetadataVersion)


class Migration(migrations.Migration):
    dependencies = [
        ("metarecord", "0044_user_relation_texts"),
    ]

    operations = [
        migrations.RunPython(
            populate_function_user_name_fields, migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_phase_user_name_fields, migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_action_user_name_fields, migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_record_user_name_fields, migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_bulk_update_user_name_fields, migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_metadata_version_user_name_fields, migrations.RunPython.noop
        ),
    ]
