name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-django-api.yml@main
    secrets: inherit
    with:
      python-version: 3.9
      postgres-major-version: 14
      use-postgis: true
      extra-commands: |
          # Spin up ES with Raudikko
          touch .docker/django/.env
          echo "ELASTICSEARCH_HOST=http://localhost:9200" >> $GITHUB_ENV
          docker compose up -d elasticsearch
          sleep 60
